apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3 # Số lượng Pod Nginx bạn muốn chạy
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest # Sử dụng image Nginx mới nhất
        ports:
        - containerPort: 80 # Cổng mà container Nginx sẽ lắng nghe
